all: genFiles gen quicksort sort_size_10 sort_size_100 sort_size_1000
genFiles: InputFileGenerator.cpp
	g++ -std=c++11 -o genFile InputFileGenerator.cpp

quicksort: Jones_Sara_QuickSort.cpp
	g++ -std=c++11 -o quicksort Jones_Sara_QuickSort.cpp

gen:
	./genFile

sort_size_10: quicksort
	./quicksort inputFiles/size10/size10_1.txt outputFiles/size10/size10_1.txt
	./quicksort inputFiles/size10/size10_2.txt outputFiles/size10/size10_2.txt
	./quicksort inputFiles/size10/size10_3.txt outputFiles/size10/size10_3.txt
	./quicksort inputFiles/size10/size10_4.txt outputFiles/size10/size10_4.txt
	./quicksort inputFiles/size10/size10_5.txt outputFiles/size10/size10_5.txt
	./quicksort inputFiles/size10/size10_6.txt outputFiles/size10/size10_6.txt
	./quicksort inputFiles/size10/size10_7.txt outputFiles/size10/size10_7.txt
	./quicksort inputFiles/size10/size10_8.txt outputFiles/size10/size10_8.txt
	./quicksort inputFiles/size10/size10_9.txt outputFiles/size10/size10_9.txt
	./quicksort inputFiles/size10/size10_10.txt outputFiles/size10/size10_10.txt
	./quicksort inputFiles/size10/size10_11.txt outputFiles/size10/size10_11.txt
	./quicksort inputFiles/size10/size10_12.txt outputFiles/size10/size10_12.txt
	./quicksort inputFiles/size10/size10_13.txt outputFiles/size10/size10_13.txt
	./quicksort inputFiles/size10/size10_14.txt outputFiles/size10/size10_14.txt
	./quicksort inputFiles/size10/size10_15.txt outputFiles/size10/size10_15.txt
	./quicksort inputFiles/size10/size10_16.txt outputFiles/size10/size10_16.txt
	./quicksort inputFiles/size10/size10_17.txt outputFiles/size10/size10_17.txt
	./quicksort inputFiles/size10/size10_18.txt outputFiles/size10/size10_18.txt
	./quicksort inputFiles/size10/size10_19.txt outputFiles/size10/size10_19.txt
	./quicksort inputFiles/size10/size10_20.txt outputFiles/size10/size10_20.txt
	./quicksort inputFiles/size10/size10_21.txt outputFiles/size10/size10_21.txt
	./quicksort inputFiles/size10/size10_22.txt outputFiles/size10/size10_22.txt
	./quicksort inputFiles/size10/size10_23.txt outputFiles/size10/size10_23.txt
	./quicksort inputFiles/size10/size10_24.txt outputFiles/size10/size10_24.txt
	./quicksort inputFiles/size10/size10_25.txt outputFiles/size10/size10_25.txt

sort_size_100: quicksort
	./quicksort inputFiles/size100/size100_1.txt outputFiles/size100/size100_1.txt
	./quicksort inputFiles/size100/size100_2.txt outputFiles/size100/size100_2.txt
	./quicksort inputFiles/size100/size100_3.txt outputFiles/size100/size100_3.txt
	./quicksort inputFiles/size100/size100_4.txt outputFiles/size100/size100_4.txt
	./quicksort inputFiles/size100/size100_5.txt outputFiles/size100/size100_5.txt
	./quicksort inputFiles/size100/size100_6.txt outputFiles/size100/size100_6.txt
	./quicksort inputFiles/size100/size100_7.txt outputFiles/size100/size100_7.txt
	./quicksort inputFiles/size100/size100_8.txt outputFiles/size100/size100_8.txt
	./quicksort inputFiles/size100/size100_9.txt outputFiles/size100/size100_9.txt
	./quicksort inputFiles/size100/size100_10.txt outputFiles/size100/size100_10.txt
	./quicksort inputFiles/size100/size100_11.txt outputFiles/size100/size100_11.txt
	./quicksort inputFiles/size100/size100_12.txt outputFiles/size100/size100_12.txt
	./quicksort inputFiles/size100/size100_13.txt outputFiles/size100/size100_13.txt
	./quicksort inputFiles/size100/size100_14.txt outputFiles/size100/size100_14.txt
	./quicksort inputFiles/size100/size100_15.txt outputFiles/size100/size100_15.txt
	./quicksort inputFiles/size100/size100_16.txt outputFiles/size100/size100_16.txt
	./quicksort inputFiles/size100/size100_17.txt outputFiles/size100/size100_17.txt
	./quicksort inputFiles/size100/size100_18.txt outputFiles/size100/size100_18.txt
	./quicksort inputFiles/size100/size100_19.txt outputFiles/size100/size100_19.txt
	./quicksort inputFiles/size100/size100_20.txt outputFiles/size100/size100_20.txt
	./quicksort inputFiles/size100/size100_21.txt outputFiles/size100/size100_21.txt
	./quicksort inputFiles/size100/size100_22.txt outputFiles/size100/size100_22.txt
	./quicksort inputFiles/size100/size100_23.txt outputFiles/size100/size100_23.txt
	./quicksort inputFiles/size100/size100_24.txt outputFiles/size100/size100_24.txt
	./quicksort inputFiles/size100/size100_25.txt outputFiles/size100/size100_25.txt

sort_size_1000: quicksort
	./quicksort inputFiles/size1000/size1000_1.txt outputFiles/size1000/size1000_1.txt
	./quicksort inputFiles/size1000/size1000_2.txt outputFiles/size1000/size1000_2.txt
	./quicksort inputFiles/size1000/size1000_3.txt outputFiles/size1000/size1000_3.txt
	./quicksort inputFiles/size1000/size1000_4.txt outputFiles/size1000/size1000_4.txt
	./quicksort inputFiles/size1000/size1000_5.txt outputFiles/size1000/size1000_5.txt
	./quicksort inputFiles/size1000/size1000_6.txt outputFiles/size1000/size1000_6.txt
	./quicksort inputFiles/size1000/size1000_7.txt outputFiles/size1000/size1000_7.txt
	./quicksort inputFiles/size1000/size1000_8.txt outputFiles/size1000/size1000_8.txt
	./quicksort inputFiles/size1000/size1000_9.txt outputFiles/size1000/size1000_9.txt
	./quicksort inputFiles/size1000/size1000_10.txt outputFiles/size1000/size1000_10.txt
	./quicksort inputFiles/size1000/size1000_11.txt outputFiles/size1000/size1000_11.txt
	./quicksort inputFiles/size1000/size1000_12.txt outputFiles/size1000/size1000_12.txt
	./quicksort inputFiles/size1000/size1000_13.txt outputFiles/size1000/size1000_13.txt
	./quicksort inputFiles/size1000/size1000_14.txt outputFiles/size1000/size1000_14.txt
	./quicksort inputFiles/size1000/size1000_15.txt outputFiles/size1000/size1000_15.txt
	./quicksort inputFiles/size1000/size1000_16.txt outputFiles/size1000/size1000_16.txt
	./quicksort inputFiles/size1000/size1000_17.txt outputFiles/size1000/size1000_17.txt
	./quicksort inputFiles/size1000/size1000_18.txt outputFiles/size1000/size1000_18.txt
	./quicksort inputFiles/size1000/size1000_19.txt outputFiles/size1000/size1000_19.txt
	./quicksort inputFiles/size1000/size1000_20.txt outputFiles/size1000/size1000_20.txt
	./quicksort inputFiles/size1000/size1000_21.txt outputFiles/size1000/size1000_21.txt
	./quicksort inputFiles/size1000/size1000_22.txt outputFiles/size1000/size1000_22.txt
	./quicksort inputFiles/size1000/size1000_23.txt outputFiles/size1000/size1000_23.txt
	./quicksort inputFiles/size1000/size1000_24.txt outputFiles/size1000/size1000_24.txt
	./quicksort inputFiles/size1000/size1000_25.txt outputFiles/size1000/size1000_25.txt
